name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: macos-14
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Done - bye!"
      
